
development:
  adapter: postgresql
  encoding: unicode
  database: todo_app_rails_development
  pool: 5
  username: scottsMac
  host: localhost
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: todo_app_rails_test
  pool: 5
  username: scottsMac
  host: localhost
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: todo_app_rails_production
  pool: 5
  username: scottsMac
  password:
